### PR TITLE
✨ Add capi into join flow

### PR DESCRIPTION
**Pull request by qiujian16**
[comment]: # ( Copyright Contributors to the Open Cluster Management project )

## Summary

so we can use
```
clusteradm join .... --capi-import --capi-cluster-name aws-cluster
```
to add a capi cluster to ocm
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
/assign @zhujian7
I did some test locally already

**Comment by zhujian7** [comment]
/lgtm
/hold
@qiujian16 should we create a new release 0.8.3 to include the repo chart URL fix before this merge?

**Comment by qiujian16** [comment]
yeah, good point.

**Pull request merged**
