### PR TITLE
:seedling: Update default versions

### PR DESCRIPTION
**Pull request by zhujian7**
[comment]: # ( Copyright Contributors to the Open Cluster Management project )

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
@mikeshng @dhaiducek @mprahl @clyang82 need you to signoff on whether these images has been built

**Comment by dhaiducek** [comment]
Thanks for the heads-up, @qiujian16! Yes, these releases are ready for Policy.

**Comment by mikeshng** [comment]
> @mikeshng @dhaiducek @mprahl @clyang82 need you to signoff on whether these images has been built

Thanks Qiu Jian. App addons are ready.

**Comment by clyang82** [comment]
multicluster controlplane is ready. Thanks

**Pull request merged**
