### PR TITLE
Add addon OWNERS files

### PR DESCRIPTION
**Pull request by dhaiducek**
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
This might be too many approvers to be onboarded all at once. I am ok if my name is removed and maybe we should only have at most 2 from policy sig.  

FYI @qiujian16

**Comment by dhaiducek** [comment]
@mikeshng Would you please re-lgtm this? It looks like the first review didn't take.

**Review by mikeshng — APPROVED** [review]
/lgtm

**Pull request merged**
