### PR TITLE
Feat: Clusteradm init supports saving commands to local file for future use

### PR DESCRIPTION
**Pull request by yue9944882**
> Signed-off-by: yue9944882 <291271447@qq.com>

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
should we just regenerate this command?

**Comment by yue9944882** [comment]
https://github.com/open-cluster-management-io/cluster-proxy/pull/34

@qiujian16 actually i'm trying to re-use the generated command from the e2e job, does that make sense?

**Comment by qiujian16** [comment]
I think it makes sense, but it seems we try to maintain how to combine join command in two places.

**Comment by yue9944882** [comment]
@qiujian16 now the generated commands are converged

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
