### PR TITLE
fix instructions regarding how to build the cli

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
@qiujian16 could you please add @itdove to https://github.com/orgs/open-cluster-management-io/people thanks!

**Comment by qiujian16** [comment]
I think I did already.... @itdove would you check and accept the invitation?

**Comment by itdove** [comment]
I think I already accepted the invite

**Comment by qiujian16** [comment]
the invitation is still pending from you.

**Comment by itdove** [comment]
Can you resend because it seems to be expired

**Pull request merged**
