### PR TITLE
modify integration test for command addon enable

### PR DESCRIPTION
**Pull request by ycyaoxdu**
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

Modify the integration test because of the directory refactor in this PR https://github.com/open-cluster-management-io/clusteradm/pull/101.
Modify tests for command `clusteradm addon enable`.

### CODE REVIEW

**Comment by xauthulei** [comment]
@qiujian16 , if we could merge this PR, there are more local error warning, Thanks 
```
unknown field values in struct literal
undeclared name: Values
...
```

**Comment by qiujian16** [comment]
I think there are still some questions in this PR?

**Comment by ycyaoxdu** [comment]
> @qiujian16 , if we could merge this PR, there are more local error warning, Thanks
> 
> ```
> unknown field values in struct literal
> undeclared name: Values
> ...
> ```

can you offer me more information about these errors and warnings? Thank you.

**Comment by ycyaoxdu** [comment]
after fix , the former integration test works.

**Comment by qiujian16** [comment]
/approve
/lgtm

thanks merge this to ensure we have a passed test.

**Pull request merged**
