### PR TITLE
add the uninstall command in readme

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: Meng <yanmxa@163.com>
Ref: https://github.com/open-cluster-management-io/clusteradm/issues/307

### CODE REVIEW

**Comment by ldpliu** [comment]
It's better to add another command "get token"

### get token
get the latest token to import a new managedcluster.
"clusteradm get token"

**Comment by yanmxa** [comment]
> It's better to add another command "get token"
> 
> ### get token
> get the latest token to import a new managedcluster. "clusteradm get token"

Done!

**Review by ycyaoxdu — APPROVED** [review]
/lgtm

**Pull request merged**
