### PR TITLE
feat: add command clusterset remove 

### PR DESCRIPTION
**Pull request by ycyaoxdu**
help remove cluster from clusterset

Opened for #133 

Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

### CODE REVIEW

**Comment by ycyaoxdu** [comment]
@qiujian16 please help to review, thanks.

**Comment by qiujian16** [comment]
should this be `clusteradm delete clusterset` ?

**Comment by ycyaoxdu** [comment]
> should this be `clusteradm delete clusterset` ?

this command `clusteradm clusteset remove` is meant to remove a cluster from a clusterset. which is an option in a  clusterset, just like the `clusteradm clusterset add` .

from my opinion, `clusteradm delete clusterset` means to delete a clusterset. we may also need `clusteradm delete clusterset` to delete a specified clusterset?

**Comment by ycyaoxdu** [comment]
#151

**Pull request closed without merging**
