### PR TITLE
fix: version break line

### PR DESCRIPTION
**Pull request by huiwq1990**
remove empty break line.

```shell
client          version :v0.5.1

server release  version :v1.22.9
default bundle  version :0.10.0
```

### CODE REVIEW

**Review by ycyaoxdu — COMMENTED** [review]
why do we need two `\n` ? @huiwq1990

**Comment by huiwq1990** [comment]
image

Currently, there are two break lines, as the VERSION file has two '\n'.

**Comment by ycyaoxdu** [comment]
/lgtm, 
could you please take a look? @qiujian16

**Comment by ycyaoxdu** [comment]
/lgtm
could you please take a look? @qiujian16

**Pull request merged**
