### PR TITLE
Update the Policy CRDs and roles

### PR DESCRIPTION
**Pull request by mprahl**
Relates:
https://github.com/open-cluster-management-io/governance-policy-propagator/pull/88
https://issues.redhat.com/browse/ACM-2946

### CODE REVIEW

**Comment by dhaiducek** [comment]
Oh man, I've been neglecting `clusteradm` updates--we're missing the consolidated sync containers and the PolicyDependency keys here. Do you want to handle all of the reconciles in this PR or would you like to merge this one and I can open a separate PR to handle the rest?

**Comment by mprahl** [comment]
@dhaiducek thanks for the reminder. I just synced the Policy CRD as well.

**Comment by mikeshng** [comment]
CC @ycyaoxdu

**Review by dhaiducek — CHANGES_REQUESTED** [review]
Thanks! Would you also remove the `sync` images from the addon-controller deployment:
```
            - name: GOVERNANCE_POLICY_SPEC_SYNC_IMAGE
              value: quay.io/open-cluster-management/governance-policy-spec-sync:{{ .BundleVersion.PolicyAddon }}
            - name: GOVERNANCE_POLICY_STATUS_SYNC_IMAGE
              value: quay.io/open-cluster-management/governance-policy-status-sync:{{ .BundleVersion.PolicyAddon }}
            - name: GOVERNANCE_POLICY_TEMPLATE_SYNC_IMAGE
              value: quay.io/open-cluster-management/governance-policy-template-sync:{{ .BundleVersion.PolicyAddon }}
```
There were some other minor role updates, but I think they're only relevant to Openshift.

**Comment by mprahl** [comment]
> name: GOVERNANCE_POLICY_SPEC_SYNC_IMAGE

@dhaiducek I thought we kept those to be able to install older versions of OCM with the latest clusteradm?

**Comment by dhaiducek** [comment]
Oh yeah--we'll definitely need them for backward compatibility. Good call.

**Comment by mprahl** [comment]
@dhaiducek I synced the addon controller and propagator ClusterRoles. Was there anything else that was out of sync?

**Review by dhaiducek — APPROVED** [review]
LGTM! Thanks for the updates, @mprahl!

**Comment by dhaiducek** [comment]
@mprahl The rebase should pick up the OWNERS file that I added, and then we can get the approval for this PR. It looks like your branch doesn't have the commit yet:
- https://github.com/open-cluster-management-io/clusteradm/pull/301

**Comment by dhaiducek** [comment]
Might need a force-push or no-op here. I'm not sure why the e2e-test failed.

**Comment by mprahl** [comment]
> Might need a force-push or no-op here. I'm not sure why the e2e-test failed.

I saw that. I just force pushed again but I noticed another open PR has the same issue.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
