### PR TITLE
allow init hub by deploy multicluster controlplane

### PR DESCRIPTION
**Pull request by ycyaoxdu**

### CODE REVIEW

**Comment by ycyaoxdu** [comment]
https://github.com/open-cluster-management-io/clusteradm/issues/323

**Comment by qiujian16** [comment]
@ycyaoxdu since we already be able to install the controlplane using helm chart, I am thinking maybe we just need to ensure we can use clusteradm to join. WDYT?

**Comment by clyang82** [comment]
for the users who are using clusteradm to build their cluster, maybe keep the same experience is better. That means the users can use clusteradm init a controlplane and then use clusteradm join to this controlplane.

**Comment by clyang82** [comment]
I do not expect to maintain the duplicated manifests in different places. The manifests should be maintained in multicluster-controlplane repo. the clusteradm command depends on the chart to init the controlplane. Is it doable or does it make sense?

**Review by qiujian16 — COMMENTED** [review]
we need to have a better code structure if we intend to use helm to install from clusteradm.

e.g.
the flags for singleton and values should be put int the separated package. For values, I think it needs to be extensible. maybe it should be "--values x=x1,y=y1"

I think it is better if we can construct a helm install interface, so we can reuse it in the future for other components like addons.

**Comment by qiujian16** [comment]
/approve
/lgtm
/hold

I seems ok in general, but I cannot go through it in detail since it is really large.
will merge it at first and resolve the following issue

**Comment by clyang82** [comment]
I am fine with the changes. Let us merge it as an initial version. we can have the following PRs to address the issues.

**Pull request merged**
