### PR TITLE
add preflight check for cluster name

### PR DESCRIPTION
**Pull request by ycyaoxdu**
fixed: https://github.com/open-cluster-management-io/clusteradm/issues/318

related: https://github.com/open-cluster-management-io/api/pull/217

### CODE REVIEW

**Comment by ycyaoxdu** [comment]
should /hold until https://github.com/open-cluster-management-io/api/pull/217 is merged

**Comment by USER0308** [comment]
@ycyaoxdu  Hi, it seem's that the regExp is not correctly work.
```
re := regexp.MustCompile(`[a-z0-9]([-a-z0-9]*[a-z0-9])?`)
	matched := re.MatchString(c.ClusterName)
	if !matched {
		return nil, []error{errors.New("validate ClusterName failed: should match `[a-z0-9]([-a-z0-9]*[a-z0-9])?`")}
	}
```
The input is `hub-cluster%^&`
Maybe you can change like this 
`re := regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)`

**Comment by ycyaoxdu** [comment]
> @ycyaoxdu Hi, it seem's that the regExp is not correctly work.
> 
> ```
> re := regexp.MustCompile(`[a-z0-9]([-a-z0-9]*[a-z0-9])?`)
> 	matched := re.MatchString(c.ClusterName)
> 	if !matched {
> 		return nil, []error{errors.New("validate ClusterName failed: should match `[a-z0-9]([-a-z0-9]*[a-z0-9])?`")}
> 	}
> ```
> 
> The input is `hub-cluster%^&` Maybe you can change like this `` re := regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`) ``

changed, thanks a lot!

**Pull request merged**
