### PR TITLE
Enable server without port

### PR DESCRIPTION
**Pull request by ohkinozomu**
Close https://github.com/open-cluster-management-io/clusteradm/issues/303
For ease of testing, I have created a new checkServer function.

Signed-off-by: Ohki Nozomu <nozomunoise@gmail.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
thanks for your contribution! would you signoff the commit by `git commit -s`?

**Comment by ohkinozomu** [comment]
@qiujian16 
Done.

**Review by ycyaoxdu — COMMENTED** [review]
/lgtm

**Pull request merged**
