### PR TITLE
Add policy-framework to hub-addon install

### PR DESCRIPTION
**Pull request by dhaiducek**
Adds `clusteradm` command for `policy-framework`:

```bash
clusteradm install hub-addon --name policy-framework
```

I'm debating how these should be named and whether we should have different names between `clusteradm install hub-addon` and `clusteradm addon enable` or use 'policy-framework' for both core components (this would match app's current behaviors). The `config-policy-controller` could remain a separate name for `clusteradm addon enable` or we could roll it in...

### CODE REVIEW

**Review by JustinKuli — APPROVED** [review]

**Comment by dhaiducek** [comment]
>I wish the first command was more like `clusteradm install hub-addon`

Yes! I couldn't quite put my finger on it, but I agree that this is the best solution.

>If/when https://github.com/open-cluster-management-io/enhancements/pull/44 is accepted and implemented, would this command be updated to deploy the policy-addon-controller as well?

Correct.

>In addition, I think we would implement addon enable commands to deploy the policy components to managed clusters, is that right? Just checking I understand the intended plan.

Yes.

**Pull request merged**
