### PR TITLE
🐛 Do not approve agent join with multiple csrs

### PR DESCRIPTION
**Pull request by qiujian16**
fixes https://github.com/open-cluster-management-io/clusteradm/issues/361

### CODE REVIEW

**Comment by ohkinozomu** [comment]
This fix doesn't address the case where CSRs were already [garbage-collected](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#request-signing-process). 
Is it an intentional decision?

**Comment by qiujian16** [comment]
I think garbage collected csr will be removed by the system. Let me double check if any state checking is missing

**Comment by ohkinozomu** [comment]
I'm concerned with the following case:

1. A CSR is created with the name cluster-1 (CSR-1)
2. CSR-1 is approved
3. CSR-1 is garbage collected
4. An another CSR is created with the name cluster-1 (CSR-2)

In this case, the number of elements in `requesters` is 1, so the condition `if len(requesters) > 1` is skipped.
Is this correct?

**Comment by qiujian16** [comment]
hrm this is a good catch.

> I'm concerned with the following case:
> 
> 1. A CSR is created with the name cluster-1 (CSR-1)
> 2. CSR-1 is approved
> 3. CSR-1 is garbage collected
> 4. An another CSR is created with the name cluster-1 (CSR-2)
> 
> In this case, the number of elements in `requesters` is 1, so the condition `if len(requesters) > 1` is skipped. Is this correct?

hrm this is a good catch. I have not considered this case.

**Pull request merged**
